function graficarPaso(~,t,xmesh,umesh,varargin)
% Parar cuando se cruza la condición de edo. est.
umesh=umesh(:);
xmesh=xmesh(:);
if nargin >= 8 ...
        && strcmp(varargin{1},'WaitBar')...
        && ishandle(varargin{2})...
        && strcmp(get(varargin{2},'Type'),'figure')...
        && strcmp(varargin{3},'TotalTime')...
        && isnumeric(varargin{4}) ...
        && isscalar(varargin{4})...
        && isreal(varargin{4})
    wb=varargin{2};
    totalTime=varargin{4};
    fraction=t(length(t))/totalTime;
    if ishandle(wb)
        messageText=findall(wb,'UserData','MainTextMessage');
    end
    estatus=['Se detendrá una vez alcanzado el Edo. Est. ó ',...
        't= ',sprintf('%02.6f',totalTime),...
        ' (',sprintf('%u',round(fraction*100)) '%)'];
    if ishandle(wb),waitbar(fraction,wb);end
    if ishandle(wb),set(messageText,'String',estatus);end
    if ~ishandle(wb)
        % Stop prematurely
        sprintf('Cancelado')
    end
end
if nargin >= 10 ...
        && strcmp(varargin{5},'AxesToPlotOn')...
        && all(ishandle(varargin{6}))
    axesArray  = varargin{6};
    uVarNo = size(umesh,1)/size(xmesh,1);
    lineObjects = -1*ones(uVarNo,2);
    if nargin > 10 ...
            && strcmp(varargin{7},'uEdoEst')...
            && isnumeric(varargin{8}) ...
            && size(varargin{8},1) == uVarNo ...
            && ishandle(wb)
        uEdoEst = varargin{8};
        uEdoEst=uEdoEst(:);
        diferencia_porcentual = norm(umesh-uEdoEst)/norm(uEdoEst)*100;
        if diferencia_porcentual <= eps*100; % u-u_estacionario = 0
            set(wb,'UserData','Steady State Reached');
        end
        messageText=findall(wb,'UserData','MainTextMessage');
        set(messageText,'String',...
            [get(messageText,'String'),'. ||u-uEst||/||uEst||=',...
            num2str(diferencia_porcentual),'%']);
    end
    if nargin > 12 ...
            && strcmp(varargin{9},'nombresDeVariables')...
            && iscell(varargin{10}) ...
            && size(varargin{10},1) == uVarNo
        nombresDeVariables = varargin{10};
    else
        nombresDeVariables = ...
            cellstr([repmat('u',uVarNo,1),int2str((1:uVarNo)')]);
    end
    for i=1:uVarNo
        subplot(axesArray(i));
        if isempty(findobj(axesArray(i),'Type','line'))
            plot(axesArray(i),...
                xmesh,...
                umesh(linspace(...
                i,i+uVarNo*(size(xmesh,1)-1),size(xmesh,1))),'-',...
                xmesh,...
                uEdoEst(linspace(...
                i,i+uVarNo*(size(xmesh,1)-1),size(xmesh,1))),'-.',...
                'LineWidth',2);
            xlabel('z, cm');
        else
            lineObjects(i,:) = findobj(axesArray(i),'Type','line');
            set(lineObjects(i,2),'XData',xmesh,...
                'YData',umesh(linspace(...
                i,i+uVarNo*(size(xmesh,1)-1),size(xmesh,1))));
            set(lineObjects(i,1),'XData',xmesh,...
                'YData',uEdoEst(linspace(...
                i,i+uVarNo*(size(xmesh,1)-1),size(xmesh,1))));
        end
        title(axesArray(i),...
            [nombresDeVariables{i},'(x,t=',sprintf('%0.3f',t(end)),')']);
    end
end
end