function wb = ventanaDeEstatus ()
stop_sign_icon =imread(fullfile(...
    ['.',filesep,'utils',filesep,'Stop_sign.png']));
stop_sign_icon(stop_sign_icon==0)=255;
DimsDePantalla=get(0,'MonitorPositions');

% Ventana de estatus
wb=waitbar(0,'Resolviendo...','CreateCancelBtn',...
    @cancelarOperacion,'Visible','off');
wbMessageText=findall(wb,'type','text');
set(wbMessageText,'Interpreter','none','UserData','MainTextMessage');
set(wb,'Name','Resolviendo...','Position',...
    [DimsDePantalla(3:4)/2-[400,300],400,300]);
wbAxesDims =...
    get(findobj(wb,'Type','axes'),'OuterPosition');
wbButtonDims =...
    get(findobj(wb,'Tag','TMWWaitbarCancelButton'),...
    'Position');
wbDimsInternas = get(wb,'Position');
alturaMaxDeSubplot = ...
    wbDimsInternas(4)-20-wbAxesDims(4)-wbButtonDims(4);
set(findobj(wb,'Type','axes'),'OuterPosition',...
    [wbDimsInternas(3)/2-wbAxesDims(3)/2,...
    wbDimsInternas(4)-20-wbAxesDims(4),...
    wbAxesDims(3),wbAxesDims(4)]);
set(findobj(wb,'Tag','TMWWaitbarCancelButton'),...
    'Position',...
    [wbDimsInternas(3)/2-wbButtonDims(3)/2,...
    wbDimsInternas(4)-20-wbAxesDims(4)-wbButtonDims(4),...
    wbButtonDims(3),wbButtonDims(4)]);
panelDesplazable = uipanel('Parent',wb,'Tag','panelDesplazable');
panelParaGraficas = uipanel('Parent',panelDesplazable,...
    'Tag','panelParaGraficas');
set(panelDesplazable,'Position',...
    [0,0,1,alturaMaxDeSubplot/wbDimsInternas(4)]);
uicontrol('Style','Slider','Parent',...
    panelDesplazable,...
    'Units','normalized','Position',...
    [0 0 0.05 1],...
    'Value',1,'Callback',{@slider_callback1,panelParaGraficas});
uipushtool(uitoolbar(wb),'CData',stop_sign_icon,'ClickedCallback',...
    @(hObject,eventdata)...
    set(get(get(hObject,'Parent'),'Parent'),'UserData','Cancelled'));
end

function slider_callback1(src,~,arg1)
val = get(src,'Value');
currentPos = get(arg1,'Position');
set(arg1,'Position',[0 1-val*currentPos(4) 1 currentPos(4)]);
end

function cancelarOperacion(hObject,~)
parent=get(hObject,'Parent');
if ishandle(parent) && strcmp(get(parent,'Type'),'figure')
    delete(parent);
elseif ishandle(hObject) && strcmp(get(hObject,'Type'),'figure')
    delete(hObject);
end
end